apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "quay.io/modh/s2i-minimal-notebook-anaconda"
    opendatahub.io/notebook-image-name: "Minimal Notebook Image using Anaconda"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with minimal dependency set to start experimenting with Jupyter environment. Uses Anaconda."
  name: s2i-minimal-notebook-anaconda
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/modh/s2i-minimal-notebook-anaconda
    from:
      kind: DockerImage
      name: quay.io/modh/s2i-minimal-notebook-anaconda:latest
    name: "py38"
    referencePolicy:
      type: Source
